name: Release Actions
on:
  push:
    branches: 
      - "main"
    tags:
      - '*'
jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: ubuntu-latest
    steps:
      #- name: Automatic Releases
      #  uses: marvinpinto/action-automatic-releases@latest
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Archive Release in ZIP
        uses: thedoctor0/zip-release@master
        with:
          echo: DB_URL
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Archive Release in Tarball
        uses: thedoctor0/zip-release@master
        with:
          echo: DB_URL
          filename: 'release.tar.gz'
          exclusions: '.gitignore'
          type: tar
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "release-${{ steps.get_version.outputs.version }}"
          artifacts: "release.zip,release.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
